name: Run Log Script

on:
  schedule:
    - cron: '*/10 1-23 * * *' # Runs every 10 mins
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master
      
    - name: Create and move to logs directory
      run: mkdir logs

    - name: Clone logs branch into logs directory
      run: |
        git clone -b logs --single-branch ${{ github.repositoryUrl }} logs/
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run log script
      run: python query.py "${{ secrets.QUERY_STR }}" "${{ secrets.PASSPHRASE }}" "${{ secrets.COOKIES }}"

    - name: Commit and push log
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add logs/*
        git commit -m "Update logs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}